No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.21
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.21
Updating build index: /Users/user/miniconda3/conda-bld

Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for virusnet-gpu
INFO:conda_build.metadata:Attempting to finalize metadata for virusnet-gpu
conda-forge/osx-64                                          Using cache
conda-forge/noarch                                          Using cache
Reloading output folder: /Users/user/miniconda3/conda-bld
Reloading output folder: /Users/user/miniconda3/conda-bld
Mamba failed to solve:
 - keras 2.12.0.*
 - numpy >=1.17.0
 - python 3.11.4.*
 - cudatoolkit
 - r-optparse 1.7.3.*
 - r-base 4.3.1.*
 - r-devtools 2.4.5.*
 - r-remotes
 - cudnn
 - tensorflow-gpu 2.12.1.*
 - r-zoo 1.8_12.*
 - h5py 3.9.0.*

with channels:

The reported errors are:
- Encountered problems while solving:
-   - nothing provides requested cudnn  - nothing provides requested tensorflow-gpu 2.12.1.*

Leaving build/test directories:
  Work:
 /Users/user/miniconda3/conda-bld/work 
  Test:
 /Users/user/miniconda3/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /Users/user/miniconda3/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_ 
  Build:
source activate  /Users/user/miniconda3/conda-bld/_build_env 


Traceback (most recent call last):
  File "/Users/user/miniconda3/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 141, in mamba_get_install_actions
    solution = solver.solve_for_action(_specs, prefix)
  File "/Users/user/miniconda3/lib/python3.10/site-packages/boa/core/solver.py", line 230, in solve_for_action
    t = self.solve(specs)
  File "/Users/user/miniconda3/lib/python3.10/site-packages/boa/core/solver.py", line 220, in solve
    raise RuntimeError("Solver could not find solution." + error_string)
RuntimeError: Solver could not find solution.Mamba failed to solve:
 - keras 2.12.0.*
 - numpy >=1.17.0
 - python 3.11.4.*
 - cudatoolkit
 - r-optparse 1.7.3.*
 - r-base 4.3.1.*
 - r-devtools 2.4.5.*
 - r-remotes
 - cudnn
 - tensorflow-gpu 2.12.1.*
 - r-zoo 1.8_12.*
 - h5py 3.9.0.*

with channels:

The reported errors are:
- Encountered problems while solving:
-   - nothing provides requested cudnn  - nothing provides requested tensorflow-gpu 2.12.1.*

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/miniconda3/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/Users/user/miniconda3/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 256, in main
    call_conda_build(action, config)
  File "/Users/user/miniconda3/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
    result = api.build(
  File "/Users/user/miniconda3/lib/python3.10/site-packages/conda_build/api.py", line 180, in build
    return build_tree(
  File "/Users/user/miniconda3/lib/python3.10/site-packages/conda_build/build.py", line 3078, in build_tree
    packages_from_this = build(metadata, stats,
  File "/Users/user/miniconda3/lib/python3.10/site-packages/conda_build/build.py", line 2038, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/Users/user/miniconda3/lib/python3.10/site-packages/conda_build/render.py", line 787, in expand_outputs
    for (output_dict, m) in deepcopy(_m).get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/Users/user/miniconda3/lib/python3.10/site-packages/conda_build/metadata.py", line 2524, in get_output_metadata_set
    conda_packages = finalize_outputs_pass(
  File "/Users/user/miniconda3/lib/python3.10/site-packages/conda_build/metadata.py", line 884, in finalize_outputs_pass
    fm = finalize_metadata(
  File "/Users/user/miniconda3/lib/python3.10/site-packages/conda_build/render.py", line 547, in finalize_metadata
    build_unsat, host_unsat = add_upstream_pins(m,
  File "/Users/user/miniconda3/lib/python3.10/site-packages/conda_build/render.py", line 409, in add_upstream_pins
    host_deps, host_unsat, extra_run_specs_from_host = _read_upstream_pin_files(m, 'host',
  File "/Users/user/miniconda3/lib/python3.10/site-packages/conda_build/render.py", line 374, in _read_upstream_pin_files
    deps, actions, unsat = get_env_dependencies(m, env, m.config.variant,
  File "/Users/user/miniconda3/lib/python3.10/site-packages/conda_build/render.py", line 131, in get_env_dependencies
    actions = environ.get_install_actions(tmpdir, tuple(dependencies), env,
  File "/Users/user/miniconda3/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 150, in mamba_get_install_actions
    raise err
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-64: {MatchSpec("cudnn")}
